# Generated by Django 4.1.2 on 2022-10-17 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время события')),
                ('event_type', models.CharField(default='visit', max_length=150, verbose_name='Тип события')),
            ],
        ),
    ]
