# Generated by Django 4.1.2 on 2022-10-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='event_type',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='action',
            field=models.CharField(default='', max_length=300, verbose_name='Действие пользователя'),
            preserve_default=False,
        ),
    ]
